// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProductTagModel _$ProductTagModelFromJson(Map<String, dynamic> json) =>
    ProductTagModel(
      id: (json['id'] as num).toInt(),
      display_name: json['display_name'] as String,
    );

Map<String, dynamic> _$ProductTagModelToJson(ProductTagModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'display_name': instance.display_name,
    };

ProductModel _$ProductModelFromJson(Map<String, dynamic> json) => ProductModel(
      id: json['id'],
      lst_price: json['lst_price'],
      active: json['active'],
      barcode: json['barcode'],
      is_product_variant: json['is_product_variant'],
      standard_price: json['standard_price'],
      volume: json['volume'],
      weight: json['weight'],
      packaging_ids: json['packaging_ids'],
      image_128: json['image_128'],
      image_256: json['image_256'],
      write_date: json['write_date'],
      display_name: json['display_name'],
      create_uid: json['create_uid'],
      create_date: json['create_date'],
      write_uid: json['write_uid'],
      description: json['description'],
      list_price: json['list_price'],
      name: json['name'],
      total_value: json['total_value'],
      sales_count: json['sales_count'],
      categ_id: json['categ_id'],
      qty_available: json['qty_available'],
      virtual_available: json['virtual_available'],
      incoming_qty: json['incoming_qty'],
      outgoing_qty: json['outgoing_qty'],
      product_tmpl_id: json['product_tmpl_id'],
      image_1920: json['image_1920'],
      image_512: json['image_512'],
      product_tag_ids:
          const ProductTagConverter().fromJson(json['product_tag_ids']),
      default_code: json['default_code'],
      product_variant_count: json['product_variant_count'],
      service_type: json['service_type'],
      visible_expense_policy: json['visible_expense_policy'],
      attribute_line_ids: json['attribute_line_ids'],
      company_id: json['company_id'],
      fiscal_country_codes: json['fiscal_country_codes'],
      pricelist_item_count: json['pricelist_item_count'],
      tracking: json['tracking'],
      show_on_hand_qty_status_button: json['show_on_hand_qty_status_button'],
      show_forecasted_qty_status_button:
          json['show_forecasted_qty_status_button'],
      uom_name: json['uom_name'],
      product_document_count: json['product_document_count'],
      purchased_product_qty: json['purchased_product_qty'],
      reordering_min_qty: json['reordering_min_qty'],
      reordering_max_qty: json['reordering_max_qty'],
      nbr_reordering_rules: json['nbr_reordering_rules'],
      nbr_moves_in: json['nbr_moves_in'],
      nbr_moves_out: json['nbr_moves_out'],
      is_favorite: json['is_favorite'],
      sale_ok: json['sale_ok'],
      purchase_ok: json['purchase_ok'],
      can_be_expensed: json['can_be_expensed'],
      type: json['type'],
      invoice_policy: json['invoice_policy'],
      is_storable: json['is_storable'],
      combo_ids: json['combo_ids'],
      service_tracking: json['service_tracking'],
      product_tooltip: json['product_tooltip'],
      lot_valuated: json['lot_valuated'],
      taxes_id: json['taxes_id'],
      tax_string: json['tax_string'],
      supplier_taxes_id: json['supplier_taxes_id'],
      valid_product_template_attribute_line_ids:
          json['valid_product_template_attribute_line_ids'],
      currency_id: json['currency_id'],
      cost_currency_id: json['cost_currency_id'],
      product_variant_id: json['product_variant_id'],
      product_properties: json['product_properties'],
      optional_product_ids: json['optional_product_ids'],
      description_sale: json['description_sale'],
      expense_policy: json['expense_policy'],
      seller_ids: json['seller_ids'],
      variant_seller_ids: json['variant_seller_ids'],
      service_to_purchase: json['service_to_purchase'],
      purchase_method: json['purchase_method'],
      description_purchase: json['description_purchase'],
      has_available_route_ids: json['has_available_route_ids'],
      route_ids: json['route_ids'],
      route_from_categ_ids: json['route_from_categ_ids'],
      responsible_id: json['responsible_id'],
      weight_uom_name: json['weight_uom_name'],
      volume_uom_name: json['volume_uom_name'],
      sale_delay: json['sale_delay'],
      property_stock_production: json['property_stock_production'],
      property_stock_inventory: json['property_stock_inventory'],
      description_pickingin: json['description_pickingin'],
      description_pickingout: json['description_pickingout'],
      property_account_income_id: json['property_account_income_id'],
      property_account_expense_id: json['property_account_expense_id'],
      property_account_creditor_price_difference:
          json['property_account_creditor_price_difference'],
    );

Map<String, dynamic> _$ProductModelToJson(ProductModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'lst_price': instance.lst_price,
      'active': instance.active,
      'barcode': instance.barcode,
      'is_product_variant': instance.is_product_variant,
      'standard_price': instance.standard_price,
      'volume': instance.volume,
      'weight': instance.weight,
      'packaging_ids': instance.packaging_ids,
      'image_128': instance.image_128,
      'image_256': instance.image_256,
      'image_1920': instance.image_1920,
      'image_512': instance.image_512,
      'write_date': instance.write_date,
      'display_name': instance.display_name,
      'create_uid': instance.create_uid,
      'create_date': instance.create_date,
      'write_uid': instance.write_uid,
      'description': instance.description,
      'list_price': instance.list_price,
      'name': instance.name,
      'total_value': instance.total_value,
      'sales_count': instance.sales_count,
      'categ_id': instance.categ_id,
      'qty_available': instance.qty_available,
      'virtual_available': instance.virtual_available,
      'incoming_qty': instance.incoming_qty,
      'outgoing_qty': instance.outgoing_qty,
      'product_tmpl_id': instance.product_tmpl_id,
      'default_code': instance.default_code,
      'product_tag_ids':
          const ProductTagConverter().toJson(instance.product_tag_ids),
      'product_variant_count': instance.product_variant_count,
      'service_type': instance.service_type,
      'visible_expense_policy': instance.visible_expense_policy,
      'attribute_line_ids': instance.attribute_line_ids,
      'company_id': instance.company_id,
      'fiscal_country_codes': instance.fiscal_country_codes,
      'pricelist_item_count': instance.pricelist_item_count,
      'tracking': instance.tracking,
      'show_on_hand_qty_status_button': instance.show_on_hand_qty_status_button,
      'show_forecasted_qty_status_button':
          instance.show_forecasted_qty_status_button,
      'uom_name': instance.uom_name,
      'product_document_count': instance.product_document_count,
      'purchased_product_qty': instance.purchased_product_qty,
      'reordering_min_qty': instance.reordering_min_qty,
      'reordering_max_qty': instance.reordering_max_qty,
      'nbr_reordering_rules': instance.nbr_reordering_rules,
      'nbr_moves_in': instance.nbr_moves_in,
      'nbr_moves_out': instance.nbr_moves_out,
      'is_favorite': instance.is_favorite,
      'sale_ok': instance.sale_ok,
      'purchase_ok': instance.purchase_ok,
      'can_be_expensed': instance.can_be_expensed,
      'type': instance.type,
      'invoice_policy': instance.invoice_policy,
      'is_storable': instance.is_storable,
      'combo_ids': instance.combo_ids,
      'service_tracking': instance.service_tracking,
      'product_tooltip': instance.product_tooltip,
      'lot_valuated': instance.lot_valuated,
      'taxes_id': instance.taxes_id,
      'tax_string': instance.tax_string,
      'supplier_taxes_id': instance.supplier_taxes_id,
      'valid_product_template_attribute_line_ids':
          instance.valid_product_template_attribute_line_ids,
      'currency_id': instance.currency_id,
      'cost_currency_id': instance.cost_currency_id,
      'product_variant_id': instance.product_variant_id,
      'product_properties': instance.product_properties,
      'optional_product_ids': instance.optional_product_ids,
      'description_sale': instance.description_sale,
      'expense_policy': instance.expense_policy,
      'seller_ids': instance.seller_ids,
      'variant_seller_ids': instance.variant_seller_ids,
      'service_to_purchase': instance.service_to_purchase,
      'purchase_method': instance.purchase_method,
      'description_purchase': instance.description_purchase,
      'has_available_route_ids': instance.has_available_route_ids,
      'route_ids': instance.route_ids,
      'route_from_categ_ids': instance.route_from_categ_ids,
      'responsible_id': instance.responsible_id,
      'weight_uom_name': instance.weight_uom_name,
      'volume_uom_name': instance.volume_uom_name,
      'sale_delay': instance.sale_delay,
      'property_stock_production': instance.property_stock_production,
      'property_stock_inventory': instance.property_stock_inventory,
      'description_pickingin': instance.description_pickingin,
      'description_pickingout': instance.description_pickingout,
      'property_account_income_id': instance.property_account_income_id,
      'property_account_expense_id': instance.property_account_expense_id,
      'property_account_creditor_price_difference':
          instance.property_account_creditor_price_difference,
    };
