// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'purchase_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PurchaseModel _$PurchaseModelFromJson(Map<String, dynamic> json) =>
    PurchaseModel(
      state: json['state'],
      invoiceCount: json['invoice_count'],
      invoiceIds: json['invoice_ids'],
      pickingCount: json['picking_count'],
      pickingIds: json['picking_ids'],
      name: json['name'],
      partnerId: json['partner_id'],
      partnerRef: json['partner_ref'],
      currencyId: json['currency_id'],
      isShipped: json['is_shipped'],
      dateOrder: json['date_order'],
      dateApprove: json['date_approve'],
      origin: json['origin'],
      companyId: json['company_id'],
      orderLine: json['order_line'],
      amountUntaxed: json['amount_untaxed'],
      amountTax: json['amount_tax'],
      amountTotal: json['amount_total'],
      notes: json['notes'],
      datePlanned: json['date_planned'],
      pickingTypeId: json['picking_type_id'],
      destAddressId: json['dest_address_id'],
      defaultLocationDestIdUsage: json['default_location_dest_id_usage'],
      incotermId: json['incoterm_id'],
      userId: json['user_id'],
      invoiceStatus: json['invoice_status'],
      paymentTermId: json['payment_term_id'],
      fiscalPositionId: json['fiscal_position_id'],
      messageFollowerIds: json['message_follower_ids'],
      activityState: json['activity_state'],
      activityUserId: json['activity_user_id'],
      activityTypeId: json['activity_type_id'],
      activityDateDeadline: json['activity_date_deadline'],
      activitySummary: json['activity_summary'],
      activityExceptionDecoration: json['activity_exception_decoration'],
      activityExceptionIcon: json['activity_exception_icon'],
      messageIsFollower: json['message_is_follower'],
      messagePartnerIds: json['message_partner_ids'],
      messageChannelIds: json['message_channel_ids'],
      messageIds: json['message_ids'],
      id: json['id'],
      displayName: json['display_name'],
      productId: json['product_id'],
      currencyRate: json['currency_rate'],
      groupId: json['group_id'],
      activityIds: json['activity_ids'],
    );

Map<String, dynamic> _$PurchaseModelToJson(PurchaseModel instance) =>
    <String, dynamic>{
      'state': instance.state,
      'invoice_count': instance.invoiceCount,
      'invoice_ids': instance.invoiceIds,
      'picking_count': instance.pickingCount,
      'picking_ids': instance.pickingIds,
      'name': instance.name,
      'partner_id': instance.partnerId,
      'partner_ref': instance.partnerRef,
      'currency_id': instance.currencyId,
      'is_shipped': instance.isShipped,
      'date_order': instance.dateOrder,
      'date_approve': instance.dateApprove,
      'origin': instance.origin,
      'company_id': instance.companyId,
      'order_line': instance.orderLine,
      'amount_untaxed': instance.amountUntaxed,
      'amount_tax': instance.amountTax,
      'amount_total': instance.amountTotal,
      'notes': instance.notes,
      'date_planned': instance.datePlanned,
      'picking_type_id': instance.pickingTypeId,
      'dest_address_id': instance.destAddressId,
      'default_location_dest_id_usage': instance.defaultLocationDestIdUsage,
      'incoterm_id': instance.incotermId,
      'user_id': instance.userId,
      'invoice_status': instance.invoiceStatus,
      'payment_term_id': instance.paymentTermId,
      'fiscal_position_id': instance.fiscalPositionId,
      'message_follower_ids': instance.messageFollowerIds,
      'activity_state': instance.activityState,
      'activity_user_id': instance.activityUserId,
      'activity_type_id': instance.activityTypeId,
      'activity_date_deadline': instance.activityDateDeadline,
      'activity_summary': instance.activitySummary,
      'activity_exception_decoration': instance.activityExceptionDecoration,
      'activity_exception_icon': instance.activityExceptionIcon,
      'message_is_follower': instance.messageIsFollower,
      'message_partner_ids': instance.messagePartnerIds,
      'message_channel_ids': instance.messageChannelIds,
      'message_ids': instance.messageIds,
      'id': instance.id,
      'display_name': instance.displayName,
      'product_id': instance.productId,
      'currency_rate': instance.currencyRate,
      'group_id': instance.groupId,
      'activity_ids': instance.activityIds,
    };
