// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stock_move_line_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StockMoveLineModel _$StockMoveLineModelFromJson(Map<String, dynamic> json) =>
    StockMoveLineModel(
      id: json['id'],
      pickingId: json['picking_id'],
      moveId: json['move_id'],
      companyId: json['company_id'],
      productId: json['product_id'],
      productUomId: json['product_uom_id'],
      productUomCategoryId: json['product_uom_category_id'],
      productCategoryName: json['product_category_name'],
      quantity: json['quantity'],
      quantityProductUom: json['quantity_product_uom'],
      picked: json['picked'],
      packageId: json['package_id'],
      packageLevelId: json['package_level_id'],
      lotId: json['lot_id'],
      lotName: json['lot_name'],
      resultPackageId: json['result_package_id'],
      date: json['date'],
      scheduledDate: json['scheduled_date'],
      ownerId: json['owner_id'],
      locationId: json['location_id'],
      locationDestId: json['location_dest_id'],
      locationUsage: json['location_usage'],
      locationDestUsage: json['location_dest_usage'],
      lotsVisible: json['lots_visible'],
      pickingPartnerId: json['picking_partner_id'],
      pickingCode: json['picking_code'],
      pickingTypeId: json['picking_type_id'],
      pickingTypeUseCreateLots: json['picking_type_use_create_lots'],
      pickingTypeUseExistingLots: json['picking_type_use_existing_lots'],
      pickingTypeEntirePacks: json['picking_type_entire_packs'],
      state: json['state'],
      isInventory: json['is_inventory'],
      isLocked: json['is_locked'],
      consumeLineIds: json['consume_line_ids'],
      produceLineIds: json['produce_line_ids'],
      reference: json['reference'],
      tracking: json['tracking'],
      origin: json['origin'],
      descriptionPicking: json['description_picking'],
      quantId: json['quant_id'],
      productPackagingQty: json['product_packaging_qty'],
      pickingLocationId: json['picking_location_id'],
      pickingLocationDestId: json['picking_location_dest_id'],
      displayName: json['display_name'],
      createUid: json['create_uid'],
      createDate: json['create_date'],
      writeUid: json['write_uid'],
      writeDate: json['write_date'],
    );

Map<String, dynamic> _$StockMoveLineModelToJson(StockMoveLineModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'picking_id': instance.pickingId,
      'move_id': instance.moveId,
      'company_id': instance.companyId,
      'product_id': instance.productId,
      'product_uom_id': instance.productUomId,
      'product_uom_category_id': instance.productUomCategoryId,
      'product_category_name': instance.productCategoryName,
      'quantity': instance.quantity,
      'quantity_product_uom': instance.quantityProductUom,
      'picked': instance.picked,
      'package_id': instance.packageId,
      'package_level_id': instance.packageLevelId,
      'lot_id': instance.lotId,
      'lot_name': instance.lotName,
      'result_package_id': instance.resultPackageId,
      'date': instance.date,
      'scheduled_date': instance.scheduledDate,
      'owner_id': instance.ownerId,
      'location_id': instance.locationId,
      'location_dest_id': instance.locationDestId,
      'location_usage': instance.locationUsage,
      'location_dest_usage': instance.locationDestUsage,
      'lots_visible': instance.lotsVisible,
      'picking_partner_id': instance.pickingPartnerId,
      'picking_code': instance.pickingCode,
      'picking_type_id': instance.pickingTypeId,
      'picking_type_use_create_lots': instance.pickingTypeUseCreateLots,
      'picking_type_use_existing_lots': instance.pickingTypeUseExistingLots,
      'picking_type_entire_packs': instance.pickingTypeEntirePacks,
      'state': instance.state,
      'is_inventory': instance.isInventory,
      'is_locked': instance.isLocked,
      'consume_line_ids': instance.consumeLineIds,
      'produce_line_ids': instance.produceLineIds,
      'reference': instance.reference,
      'tracking': instance.tracking,
      'origin': instance.origin,
      'description_picking': instance.descriptionPicking,
      'quant_id': instance.quantId,
      'product_packaging_qty': instance.productPackagingQty,
      'picking_location_id': instance.pickingLocationId,
      'picking_location_dest_id': instance.pickingLocationDestId,
      'display_name': instance.displayName,
      'create_uid': instance.createUid,
      'create_date': instance.createDate,
      'write_uid': instance.writeUid,
      'write_date': instance.writeDate,
    };
